//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public string Name { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string TypeName { get; set; }
    }
}
