//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeVATChange
    {
        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public int VatId { get; set; }
        public System.DateTime EffectiveDate { get; set; }

        public virtual ProductType ProductType { get; set; }
        public virtual ProductVAT ProductVAT { get; set; }
    }
}
