//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsHistoryExtended
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Supplier { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string UserName { get; set; }
        public int IdProduct { get; set; }
        public string Description { get; set; }
        public string ProductType { get; set; }
        public int Quantity { get; set; }
    }
}
